name: 'tmbuild action'
description: 'Wrapper around tmbuild'
inputs:
  clang:
    description: "Uses clang on windows?"
    default: false
  mode:
    description: 'Building the Engine or a Plugin. Values: Engine or Plugin'
    default: "Engine"
  config:
      description: 'Debug or Release'
      default: "Debug"
  tmbuild_repository:
    description: "repository used to download the dependencies for tmbuild"
    default: "https://ourmachinery.com/lib/"
  libpath:
    description: "path to the libs folder. If not provided the env variable TM_SDK_LIB_DIR will be used"
    default: "./lib"
  binary_repository:
    default: Null
    description: "repository used to download the engine binary"
  project:
    description: 'Will build a specific project'
    default: ""
  package:
    description: 'Package the engine based on the provided package file.'
    default: ""
  gendoc:
    description: 'Generates a doc'
    default: false
  genhash:
    description: 'Runs the hash tool before build'
    default: false
  gennode:
    description: 'Runs the node gen tool before build'
    default: false
  cache:
    default: true
  tests:
    default: true
  path:
    default: "./"
  unit-tests:
    description: 'Runs a specific unit tests'
outputs:
  result: # id of output
    description: 'the result of the build step'
  errors:
    description: 'returns only the errors'
  warnings:
    description: 'returns only the warnings'
  tmbuild-cache-key:
    description: 'returns the tmbuild cache key'
  tmbuild-cache-path:
    description: 'returns the tmbuild cache path'
runs:
  using: 'node12'
  main: 'index.js'
