name: 'tmbuild action'
description: 'Wrapper around tmbuild'
inputs:
# build settings:
  clang:
    description: "Uses clang on windows?"
    default: false
  buildconfig:
      description: 'Debug or Release'
      default: "Debug"
  # options
  build:
    description: 'Will build tm'
    default: true
  package:
    description: 'Package the engine'
    default: ""
  gendoc:
    description: 'Will generate a doc'
    default: false
  buildtmbuild:
      description: 'Will build tmbuild itself'
      default: false
  # config optional:
  libjsonpath:
      description: 'path to libs.json'
      default: "./"
  libpath:
      description: 'path to libs'
      default: "./lib"
  repo:
      description: 'repository for the dependencies'
      default: "https://ourmachinery.com/lib/"
  tmurl:
      description: 'Url to the engines zip'
      default: ""
  project:
    description: 'Will build a specific project'
    default: ""
  # cache settings:
  cacheVersion:
    default: "1.0.0"
  useCache:
    default: true
  cacheLibs:
    description: 'Will cache the ./lib folder after tmbuild ran to cache all libs'
    default: true
  # artifacts:
  artifact:
    description: 'Stores build artifacts'
    default: false
  packageArtifact:
    description: 'Stores package artifacts'
    default: false     
outputs:
  result: # id of output
    description: 'the result of the build step'
runs:
  using: 'node12'
  main: 'index.js'
